ficep_planning_homepage:
    path:     /planning/{week}/{year}
    defaults: { _controller: FicepPlanningBundle:Default:index }

    
ficep_planning_addTechnician:
    path:     /technician/add
    defaults: { _controller: FicepPlanningBundle:Technician:add }
ficep_planning_listTechnician:
    path:     /technician/list/{id}/{page}
    defaults: { _controller: FicepPlanningBundle:Technician:list, id: all, page: 1 }
ficep_planning_deleteTechnician:
    path:     /technician/delete/{id}
    defaults: { _controller: FicepPlanningBundle:Technician:delete }
ficep_plannning_editTechnician:
    path:     /technician/edit/{id}
    defaults: { _controller: FicepPlanningBundle:Technician:edit }

    
ficep_planning_addCustommer:
    path:     /custommer/add
    defaults: { _controller: FicepPlanningBundle:Custommer:add }
ficep_planning_listCustommer:
    path:     /custommer/list/{id}/{page}
    defaults: { _controller: FicepPlanningBundle:Custommer:list, id: all, page: 1}
ficep_planning_deleteCustommer:
    path:     /cutommer/delete/{id}
    defaults: { _controller: FicepPlanningBundle:Custommer:delete }
ficep_planning_editCustommer:
    path:     /custommer/edit/{id}
    defaults: { _controller: FicepPlanningBundle:Custommer:edit }
    
    
ficep_planning_addMachine:
    path:     /machine/add
    defaults: { _controller: FicepPlanningBundle:Machine:add }
ficep_planning_listMachine:
    path:     /machine/list/{id}/{page}
    defaults: { _controller: FicepPlanningBundle:Machine:list, id: all, page: 1}
ficep_planning_deleteMachine:
    path:     /machine/delete/{id}
    defaults: { _controller: FicepPlanningBundle:Machine:delete }
ficep_planning_editMachine:
    path:     /machine/edit/{id}
    defaults: { _controller: FicepPlanningBundle:Machine:edit }
    

