<?php

namespace Ficep\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CustommerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustommerRepository extends EntityRepository
{
		public function getCustommers($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('a')->getQuery();
		$query->setFirstResult(($page-1) * $nbPerPage)
		      ->setMaxResults($nbPerPage);
	  	return new Paginator($query);
	}
}
