<?php

namespace Ficep\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TechnicianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicianRepository extends EntityRepository
{
}
